spring:
  config:
   import: optional:file.env[.properties] #for reading props from env file
server: 8081

grpc:
  client:
    GLOBAL:
      address: ${GRPC_HOST}
      negotiation-type: plaintext

push:
  batch-size: ${BATCH_SIZE}